### ISSUE TITLE
Ordering in APIs

### ISSUE THREAD

**Issue by Roxe322** [samanthasgroup/django-webapps#103]
Discuss default ordering for models, or in views, or let front end apply custom ordering by fields.

**Comment by lemontree210** [comment]
@ivanBarinsky I think this is a question for you 😉

**Comment by ivanBarinsky** [comment]
yeah, i agree with @Roxe322 , tooljet lets you sort the table by any field you want, i'd say the default ordering should be by the date created (i haven't had a very thorough look at the backend code, but im assuming the ID's are sequential. so sorting these in descending order should work fine)
