### ISSUE TITLE
API view to return possible log event types

### ISSUE THREAD

**Issue by ivanBarinsky** [samanthasgroup/django-webapps#120]
This should definitely be lower on the priorities list, but it would be nice to have a view that would return a list of possible log event types and their descriptions for a type of entity, smth like `/public/log_event_types/`

**Comment by lemontree210** [comment]
The question is why exactly that is needed. As @Roxe322 rightly pointed out, ToolJet should be unaware of the types of log events that backend has. We will be planning for ToolJet to send "agnostic" requests to URLs such as e.g. `api/group/start/` to start studies in a group. And then the backend will take care of the statuses and log events without ToolJet knowing what types of them there are. I think this is a very sane approach.

But just in case, [here](https://github.com/samanthasgroup/django-webapps/blob/master/api/models/choices/log_event_types.py) is the module with the current collection of log event types.

**Comment by ivanBarinsky** [comment]
ah, i see, i think i may have jumped the gun a bit with mocking up log events in tooljet. I originally raised the issue to populate the dropdown selectors for picking the event type but looks like that isnt necessary 👍
