### ISSUE TITLE
API view: create a group and add students and teachers to it

### ISSUE THREAD

**Issue by lemontree210** [samanthasgroup/django-webapps#123]
When a coordinator creates a group in ToolJet:

## Create/change objects
- create new `Group` with following attributes passed from the dashboard: 
  - language and level
  - availability slots (no exact days and times yet)
  - lesson duration (because a teacher can determine this, but the coordinator should select some initial value based on their knowledge of the business processes: e.g., advanced groups tend to have longer classes)
  - (note that `telegram_chat_url` is **not** assigned at this point because this is just a tentative group)
- assign this `Coordinator` (identified by their email) to this `Group`
- add selected `Student`s and `Teacher`s to this `Group`

Note that the backend must know exactly who is added to the group as a student and who is added as a teacher, because in rare cases people can combine these roles (in the whole project, not in one group, of course).

> @ivanBarinsky Depending on what is doable in ToolJet, you can either create 10 fields with drop-down lists for students and 2 for teachers - or just two fields if "add more" button can be created (that adds one more field).
> @Roxe322 I don't think we will implement some limitations on number of students depending on their age, it's too complicated, and the logic is not rigid enough. Let humans and bot control this.

## Create log events

Types of `LogEvent`s to be created:

- coordinator(s): none (group is still pending, so it isn't confirmed or working, hence nothing significant has happened)
- group: `FORMED`
- students: `GROUP_OFFERED`
- teacher(s): `GROUP_OFFERED`

## Set statuses
- group: `PENDING`
- coordinator: no status change
- students: `GROUP_OFFERED`
- teachers: `GROUP_OFFERED`

Remember to update `status_since` to current time in UTC for all relevant entities.

**Comment by Auch-Auch** [comment]
Noticed some schema issues:

1. `telegram_chat_url` has a unique constraint but at the same time it can not be null. So it is impossible to create Group without specifying `telegram_chat_url`.
2. I think everything with `*_former` should have a default value because during first creation group has no any `*_former` items.

**Comment by lemontree210** [comment]
Thanks for the valuable insight!
>     1. `telegram_chat_url` has a unique constraint but at the same time it can not be null. So it is impossible to create Group without specifying `telegram_chat_url`.

OK, I see at least 2 possible solutions here. Either we finally decide to split `Group` into two models that will share some attributes via an abstract model ("finalized group" vs. "tentative group", and only the former will have `telegram_chat_url` field) or we make this field `blank=True, null=True` and add a required item to `data` passed in a `POST` request so that a coordinator can't start a group without creating a Telegram group first and passing in its URL. Right now I can see both options as viable...

>     2. I think everything with `*_former` should have a default value because during first creation group has no any `*_former` items. Or, for example, we can set `teacher` to `teacher_former` during creation if that is acceptable by business logic.

Hm... given the fact that they are all many-to-many relationships, there shouldn't be a problem to just leave all of the `..._former` fields blank?

**Comment by Auch-Auch** [comment]
> OK, I see at least 2 possible solutions here. Either we finally decide to split `Group` into two models that will share some attributes via an abstract model ("finalized group" vs. "tentative group", and only the former will have `telegram_chat_url` field) or we make this field `blank=True, null=True` and add a required item to `data` passed in a `POST` request so that a coordinator can't start a group without creating a Telegram group first and passing in its URL (i.e. it will be optional in the model but enforced via an API view we're creating in this issue here). Right now I can see both options as viable...
> 
Yes, I think for the MVP we can just set `null=True`
>Hm... given the fact that they are all many-to-many relationships, there shouldn't be a problem to just leave all of the ..._former fields blank?
>
Yep, but we also need to set `blank=True` because currently it is `False`

**Comment by lemontree210** [comment]
Alright, `blank=True` then, of course


сб, 8 июл. 2023 г., 17:56 Aleksandr Pastukhov ***@***.***>:
