### ISSUE TITLE
[DISCUSSION] Add pagination or caching to API views that can return too many results

### ISSUE THREAD

**Issue by lemontree210** [samanthasgroup/django-webapps#168]
As diagnosed by @Auch-Auch , even several hundred records already take around 5 seconds to be returned to an API client. 

This could mean that:
- For views such as lists of groups, students and teachers, pagination has to be done in the backend, not in the dashboard as it is now
- To allow filtering, we will have to allow passing parameters to the `GET` request (substring to search for)

@ivanBarinsky this will make your workflow more complex, but it seems that it is inevitable, given the waiting time that will be closer to a minute as we get more and more students, teachers etc.

Let's evaluate the effort and other opportunities.

**Comment by lemontree210** [comment]
The following filters will be required IMO:

## `Group`
- availability_slots_for_auto_matching
- is_for_staff_only
- language_and_level
- lesson_duration_in_minutes
- status
- schedule (combined from all weekday fields)

Additionally:
- contains between x and y students
- contains between x and y teachers (some groups are taught by more than 1 teacher)

## `Student`
Model fields:
- age_range
- availability_slots
- can_read_in_english
- is_member_of_speaking_club
- non_teaching_help_required
- status
- teaching_languages_and_levels

Additionally:
- number of groups the student is attending (will be 1 for the absolute majority, but a need may arise to filter out students that attend more than 1 group)
- has been waiting for group (has status `AWAITING_OFFER`) for more than x days/weeks

## Teacher
Model fields:
- availability_slots
- has_prior_teaching_experience
- non_teaching_help_provided
- simultaneous_groups (this is _not_ the actual number of groups the teacher _is_ teaching: this is how many groups they were _ready to teach_ when they registered)
- status
- student_age_ranges
- weekly_frequency_per_group

These boolean fields can be put together in a list for an API call
- peer_support_can_check_syllabus
- peer_support_can_host_mentoring_sessions
- peer_support_can_give_feedback
- peer_support_can_help_with_childrens_groups
- peer_support_can_provide_materials
- peer_support_can_invite_to_class
- peer_support_can_work_in_tandem

Additionally
- number of groups the teacher is teaching
- has been waiting for group (has status `AWAITING_OFFER`) for more than x days/weeks

**Comment by lemontree210** [comment]
@ivanBarinsky as you can see, that's a lot of fields and probably a lot of effort. @Auch-Auch,  @Roxe322 tried querying different numbers of records with `curl` and it turns out that it takes around 12 seconds to get 3000 students. Maybe it's not too long, especially in MVP?

(I'm only talking about students here because they are the most numerous entities, but the logic applies to groups and teachers as well.)

The number of students in the database will continue to grow, obviously, but in the dashboard we only have to display students that are currently studying / on leave / waiting for the group etc., i.e. not those who finished and left the project. So I don't expect that number to exceed 5000 at any given time.

We should just make sure that the list view that we originally added in #57 returns students with statuses other than `FINISHED_LEFT`, `BANNED`, `LEFT_PREMATURELY` and `NO_RESPONSE` and then maybe create separate views for "archived students" (for `NO_RESPONSE` at any case).

So instead of pagination, we could split the students into categories:
- active
- not responding (with status `NO_RESPONSE`)
- left the project

The last category may not even be in the dashboard at all, only in Django admin site.

Maybe we can further speed up the process by adding [caching](https://www.django-rest-framework.org/api-guide/caching/), as @Roxe322 suggests.

**Comment by ivanBarinsky** [comment]
ok that approach sounds good to me and an extra thumbs up on the caching side, sadly tooljet doesnt seem to provide any kind of caching. Re filtering, i think if we "rank" them by priority (with things like ID's obv taking the first place), we can get it done relatively painlessly, i imagine this is a pretty trivial task for django and will require some research on the tooljet side, but i dont expect it to be a huge task

**Comment by lemontree210** [comment]
> We should just make sure that the list view that we originally added in #57 returns students with statuses other than `FINISHED_LEFT`, `BANNED`, `LEFT_PREMATURELY` and `NO_RESPONSE` and then maybe create separate views for "archived students" (for `NO_RESPONSE` at any case).

Created issue #158

**Comment by lemontree210** [comment]
closing in favor of #219

**Comment by lemontree210** [comment]
closing the rest of the issue in favor of #219
