### ISSUE TITLE
API view: discard the tentative group if the teacher didn't confirm or not enough students confirmed

### ISSUE THREAD

**Issue by lemontree210** [samanthasgroup/django-webapps#175]
When a coordinator (from dashboard) or bot send a request stating that a group they created cannot be confirmed because not enough students confirmed their participation or a teacher didn't confirm it.

## Preparation: Delete/add log event types 
- [x] Delete two `NOT_CONFIRMED_...` types of `GroupLogEvent`: we will just discard the tentative group completely, deleting it from database, so no additional log events are actually needed for it.
- [x] At the same time, a teacher/student has to get a log event when they do not decline, but then not enough students confirm their readiness to study.

## 1. Create log events:

Beside individual log events for students and teachers that will be listed in other issues (relating to their individual reactions to an offer), create following `StudentLogEvent`s and `TeacherLogEvent`s of type `TENTATIVE_GROUP_DISCARDED`. As a `.comment`, put a reason why. We can standardize these comments in constants. Right now I can only think of the following options:
- "teacher_declined"
- "teacher_did_not_react"
- "not_enough_students_accepted"

No log event is needed for the coordinator.

## 2. Remove coordinator, students and teacher from the group, then delete the group in question

Actually, I'm not 100% sure what happens if we delete a group. I think that it should automatically disappear from `coordinator/student/teacher.groups`. If it does, there's no need to remove them manually before deleting the group. Since the group was only tentative, there's no need to transfer anything to `..._former` fields.

## 3. Set statuses
- Coordinators' statuses change depending on the number of groups each of them has:
  - if it is below threshold: `WORKING_BELOW_THRESHOLD`
  - if it is above threshold and below the limit: `WORKING_OK`
  - if it has reached the limit: `WORKING_LIMIT_REACHED`
- Its students' status changes to `NO_GROUP_YET` (actually it's theoretically possible for a student to attend two groups in the future (which means that discarding one group wouldn't necessarily mean they are not studying in any group), but it is definitely not planned at this moment and it should be rare)
- Its teachers' statuses change depending on the number of the groups they were ready to teach simultaneously:
  - if it is `0`: `NO_GROUP_YET`
  - if it is more then zero:  `WORKING` 

Remember to update `status_since` to current time in UTC in objects (where applicable).

**Comment by Auch-Auch** [comment]
> * [x]  At the same time, a teacher/student has to get a log event when they do not decline, but then not enough students confirm their readiness to study.

So for this, we need some discard type param or separate views to understand the reason, right? And also small clarification, so teacher and student can decline a group or only teacher? This part is a little bit confusing.

> Delete two NOT_CONFIRMED_... types of GroupLogEvent: we will just discard the tentative group completely, deleting it from database, so no additional log events are actually needed for it.

Should we then delete all logs for this group? Otherwise I do not see a reason for deleting last logs, maybe we can add another log stating that group is deleted and provide a reason?

**Comment by lemontree210** [comment]
@Auch-Auch I have created a draft PR #221 where I already replaced some log event types. I'm still thinking about the rest, but we can think together :) 

> we need some discard type param or separate views to understand the reason, right?

You are absolutely correct in that we want to record the reason why the student/teacher declined an offer. The act of declining an offer itself will be in a separate view, because it will be a request sent by the bot to the back-end. I don't think that any special parameter is needed, I think that at least for now we can just use the `comment` field of `LogEvent`. So when user declines an offer, the reason for that action will be recorded in `.comment` of that event. And when a `Group` gets discarded, then a reason for that can be put into the log events for respective students and teacher as their `.comment`.

Now, as for deleting of log events. For now I think that:
- `GroupLogEvent` should remain connected to `Group` with `models.CASCADE` parameter. As far as I understand, this means that when a `Group` is deleted, all `GroupLogEvent`s connected to that group are also automatically deleted. I think this is exactly what we want because the number of tentative groups can be extremely high. One counterargument would be that it would make debugging hard, so maybe we should keep the tentative groups and only delete them after a while, I don't know. (And I don't know if it's worth spending time programming this logic now.)
- `StudentLogEvent` and `TeacherLogEvent` should, I think, be connected with `Group` with `models.PROTECT` parameter as opposed to `models.CASCADE` we have there now. I think that it will be important to still have this information in a student's or a teacher's log even if the tentative group is deleted.

> teacher and student can decline a group or only teacher?

I see you deleted this but I'll reply anyway :) Yes, both students and teachers can decline offers.

**Comment by Auch-Auch** [comment]
I see, so for this issue we should implement a view for student, teacher, group, right?

**Comment by Auch-Auch** [comment]
> StudentLogEvent and TeacherLogEvent should, I think, be connected with Group with models.PROTECT parameter as opposed to models.CASCADE we have there now. I think that it will be important to still have this information in a student's or a teacher's log even if the tentative group is deleted.

I agree.

> GroupLogEvent should remain connected to Group with models.CASCADE parameter. As far as I understand, this means that when a Group is deleted, all GroupLogEvents connected to that group are also automatically deleted. I think this is exactly what we want because the number of tentative groups can be extremely high. One counterargument would be that it would make debugging hard, so maybe we should keep the tentative groups and only delete them after a while, I don't know. (And I don't know if it's worth spending time programming this logic now.)

Hmm, this is kind of tricky but the best solution is indeed to delete declined group and corresponding logs after some time.
In NoSQL it is super simple to handle with TTL indexes but here you need separate service for that, which might be an overengineering and we can just delete it right away.

**Comment by lemontree210** [comment]
> I see, so for this issue we should implement a view for student, teacher, and group with a comment param, right?

Correct :) Or the param could be called `reason`, but at least for now we will be saving it in `...LogEvent.comment`

Also, I have just updated the description of the issue, feel free to re-read and comment.

**Comment by lemontree210** [comment]
> Hmm, this is kind of tricky but the best solution is indeed to delete declined group and corresponding logs after some time. In NoSQL it is super simple to handle with TTL indexes but here you need separate service for that, which might be an overengineering and we can just delete it right away.

Yep, let's delete it right away. We'll have student/teacher log events to inspect anyway. Maybe, we can automatically add some short but useful auxiliary information to the `.comment` of their log events. E.g. 

`f"Group of level {group.level} suggested availability slots {group.availability_slots}, managed to collect {group.students.count()} students. Reason for discarding: {json_data.comment}"`.

**Comment by Auch-Auch** [comment]
> Actually, I'm not 100% sure what happens if we delete a group. I think that it should automatically disappear from coordinator/student/teacher.groups. If it does, there's no need to remove them manually before deleting the group. Since the group was only tentative, there's no need to transfer anything to ..._former fields.

Yes, as far as I understand, the record in the junction table will be deleted and it will affects students/teachers/coordinators of that group

>Beside individual log events for students and teachers that will be listed in other issues (relating to their individual reactions to an offer), create following StudentLogEvents and TeacherLogEvents of type TENTATIVE_GROUP_DISCARDED. As a .comment, put a reason why. We can standardize these comments in constants. Right now I can only think of the following options:
"teacher_declined"
"teacher_did_not_react"
"not_enough_students_accepted"

I will create a Enum for that, so that we can compare it if needed

**Comment by Auch-Auch** [comment]
One more clarification for me, discard group endpoint should be in internal router or in dashboard as well? Based on description seems like it should be in both.

**Comment by lemontree210** [comment]
> One more clarification for me, discard group endpoint should be in internal router or in dashboard as well? Based on description seems like it should be in both.

Correct, in both. Although in the standard workflow the dashboard API handle should basically never be used, we have to create it just in case something is wrong with the bot. And maybe for the sake of "least astonishment" (otherwise we will forget and then think, why do we have a "confirm" handle, but not the "discard" handle?)
