### ISSUE TITLE
API view filter: show students who are awaiting coordinator's decision

### ISSUE THREAD

**Issue by lemontree210** [samanthasgroup/django-webapps#237]
The issue originally was that coordinators must be able to easily see students that finished studying so that they can perform one of (at least) two actions: remove them from the project or mark them as awaiting another group (see [discussion](https://github.com/samanthasgroup/django-webapps/pull/235#discussion_r1306652201) in #235 for how @dont-text-me saw implementation for the dashboard). 

However, after [discussion](https://github.com/samanthasgroup/django-webapps/issues/237#issuecomment-1712574001) with @Roxe322, I suggest creating a new `project_status` for `Student`, called `AWAITING_DECISION`, which for now will be applied to students that finished the group (hence a follow-up on #235 will have to be created with amended `project_status`).

**Comment by Roxe322** [comment]
I don't like an idea of relying to multiple things for filtering such students (I mean latest log event + current status) as you discussed .

I suggest to add special project status (or maybe situational?) for such students. Something like "group_finished_awaiting_for_info" . Also in [this](https://github.com/samanthasgroup/django-webapps/blob/9a83722b51ebc1a574c936b96d2d274ed86ec701/api/processors/actions/group/finish.py#L57) place I suggest to do some `if` statement. We should filter students that are studying in any other group and set status which is suitable for that one (I'm not sure how to calculate it, but maybe just "studying"), and if student doesn't studying in any other group - we should set some new status.

And we already have a filter by project status in DashboardStudentWithPersonalInfoViewSet. Maybe it will also be needed to add filter by situational status there

**Comment by lemontree210** [comment]
I think that's exactly what we were discussing [here](https://github.com/samanthasgroup/django-webapps/pull/235#discussion_r1306652201), I originally proposed something I called "limbo status", but there were objections to that.

**Comment by lemontree210** [comment]
Here is my suggestion so that we don't block development here. Let's create a universal project status that will be called something like `AWAITING_DECISION` or `ON_HOLD` that would describe any situation in which a coordinator must take some sort of decision before the student continues the studies or leaves the project. 

For example, another situation that could trigger this project status would be a student missing 3 classes without notifying the teacher.

@Auch-Auch any objections?
