### ISSUE TITLE
API view: student missed class with vs. without notifying the teacher

### ISSUE THREAD

**Issue by lemontree210** [samanthasgroup/django-webapps#263]
When a coordinator (from dashboard) sends a request stating that the given student missed a class:

## Create log events

Types of `LogEvent`s to be created for `Student`:

- `MISSED_CLASS_NOTIFIED` if student notified the teacher in advance
- `MISSED_CLASS_SILENTLY` if student hadn't notified the teacher

Obviously, the backend will know nothing about the fact of notification (or lack thereof), so the coordinator just has to push a respective button (or whatever) in the dashboard (after being notified by the teacher).

Basically this issue is about creating two views in one (e.g. "missed class" view with parameter of "notified" set to true or false).

## Set `situational_status` for `Student` if conditions are met

If `STUDENT_CLASS_MISS_LIMIT` has been reached (e.g. if, together with this one, there is a total of `STUDENT_CLASS_MISS_LIMIT` log events of type `MISSED_CLASS_SILENTLY` for this student over the past 2 weeks), set `situational_status` to `NOT_ATTENDING`.

> [!note]
> Why "over the past 2 weeks"? Because actually the owners want to set status to `NOT_ATTENDING` if 3 classes **in a row** were missed. But there's no way for us of knowing that, because there is no event `ATTENDED_CLASS`. So I suggest saying that if a student missed 3 classes over the past 2 weeks, then with our default frequency of 2 classes per week it should be roughly equivalent to missing 3 classes in a row. We can put `2` (for 2 weeks) in a constant as well, along with a shorter version of this explanation here as its docstring.

> [!important]
> Events of type `MISSED_CLASS_NOTIFIED` don't count towards setting `situational_status` to `NOT_ATTENDING`

Remember to update `status_since` to current time in UTC in objects (where applicable).

**Comment by Auch-Auch** [comment]
If I understand correctly, we also need to know the group he is currently attending, right?

**Comment by lemontree210** [comment]
> If I understand correctly, we also need to know the group he is currently
attending, right?

Yes, of course we need to know the id of their group
