### ISSUE TITLE
API view: `Student` or `Teacher` went on leave

### ISSUE THREAD

**Issue by lemontree210** [samanthasgroup/django-webapps#267]
## Add log event types before creating serializers and views

Please add the following log event types to `StudentLogEventType`, `TeacherLogEventType` and `TeacherUnder18LogEventType` (they can be copied from `CoordinatorLogEventType`)

```py
    GONE_ON_LEAVE = "gone_on_leave", "Gone on leave"
    RETURNED_FROM_LEAVE = "returned_from_leave", "Returned from leave"
```

When a coordinator from dashboard or bot sends a request stating that a student or a teacher went on leave:

## Create log events

Type of `LogEvent`s to be created: `GONE_ON_LEAVE`

## Set statuses
`project_status` is to be set to `ON_LEAVE`.

> [!Important]
> Remember to update `status_since` to current time in UTC.

**Comment by Auch-Auch** [comment]
Do we need to know the current group of student?
