### ISSUE TITLE
API view: show (number of) students available for given day/time slots

### ISSUE THREAD

**Issue by lemontree210** [samanthasgroup/django-webapps#276]
After some consultation with UX we realized that the following workflow will be optimal for coordinators when creating a tentative group in the dashboard:

1. Coordinator finds a teacher and selects him/her. Coordinator chooses language, age group(s), level and communication language.
2. Then, there are some pairs of slots that the coordinator wants to explore to find out which pair is best for creating a tentative group.
3. When the coordinator chooses a pair of slots, the dashboard will send a request to the backend, and the backend must return **the number of students** (with matching parameters and project_status `NO_GROUP_YET`), so that the coordinator can choose the most promising option that will fit as many students as possible.
4. This API view can return the IDs and names of the students as well (IDs for sending back to the backend when the tentative group is created, names for displaying in the form on the next stage). The question is, however, whether ToolJet can store the data (I think that only the data from the latest API request will need to be saved in some sort of variable) or whether another API request is needed when the coordinator chooses the pair of slots. If IDs and names are returned, maybe the number is not needed because the size of the list can be calculated in ToolJet.

**Comment by lemontree210** [comment]
@dont-text-me comments are welcome :)

**Comment by Auch-Auch** [comment]
What does "pair of slots" mean? So as query params we should use 1 time slot id or several ones?

**Comment by dont-text-me** [comment]
> What does "pair of slots" mean? So as query params we should use 1 time slot id or several ones?

In the UI, coordinators are limited to 2 time slots when creating a potential group, so there will always be exactly 2 time slot id's in the request👌
