### ISSUE TITLE
API view: determine next step for `Student` after group finished studies

### ISSUE THREAD

**Issue by lemontree210** [samanthasgroup/django-webapps#292]
When a group finishes studies (#234, fixed by #235), the students that were in this group still retain `STUDYING` status (see [discussion](https://github.com/samanthasgroup/django-webapps/pull/235/files#r1306648977) in #235, where we decided not to create a "limbo" status). Hence, please delete this `project_status`: `AWAITING_DECISION = "awaiting_decision", "Awaiting decision"`

After this, we need to:

- show to coordinators in TJ dashboard the list of students that are awaiting decision
Maybe we also have to show some mark in the student's profile. Anyway, maybe this can be done without an additional view (a piece of code in TJ could check if the student has status `STUDYING` and at the same time no groups). @dont-text-me what do you think?
- in student's profile, add functionality for the coordinator to choose the next action: either to mark the student as leaving the project completely, or put them back into the queue (maybe with an updated language level)

So the tasks regarding API views would be the following (a separate issue can be created from each task, just click on a circle right of the task)
- [ ] API view: return students with status `STUDYING` but no groups
- [ ] API view: mark student as leaving the project completely by creating log event of type `FINISHED_AND_LEAVING` and setting `project_status` to `FINISHED`.
- [ ] API view: return the student to the waiting queue by creating log event of type `AWAITING_OFFER` and setting `project_status` to `NO_GROUP_YET`.

**Comment by Auch-Auch** [comment]
Can you, please, clarify what `return the student to the waiting queue` means? @lemontree210  Set status to AWAITING_DECISION?

**Comment by Auch-Auch** [comment]
Also, what status should be used for `mark student as leaving the project completely`? Or what does mark mean then?

**Comment by lemontree210** [comment]
> Can you, please, clarify what `return the student to the waiting queue` means? @lemontree210 Set status to AWAITING_DECISION?

Erm, no, we should have deleted this `project_status` since it's this limbo status we decided not to use 😄 

By returning the student to the waiting queue I mean setting `project_status` to `NO_GROUP_YET` and creating log event of type `AWAITING_OFFER`.

**Comment by lemontree210** [comment]
> Also, what status should be used for `mark student as leaving the project completely`? Or what does mark mean then?

It means creating log event of type `FINISHED_AND_LEAVING` and setting `project_status` to `FINISHED`.

**Comment by lemontree210** [comment]
@Auch-Auch thank you, I added these notes to the issue description.
