### ISSUE TITLE
API view: offer a student to join an existing group

### ISSUE THREAD

**Issue by lemontree210** [samanthasgroup/django-webapps#298]
When a coordinator from dashboard sends a request stating that they want to add a student to a group that is already studying:

## Create log events

Types of `LogEvent`s to be created:

- student: `GROUP_OFFERED` (with `to_group` set to this group)

## Set statuses
- students: no change in `project_status`, `situational status` becomes `GROUP_OFFERED`

> [!Note]
> Remember to update `status_since` to current time in UTC in objects (where applicable).

Obviously, the view must receive student ID and group ID from the dashboard.

**Comment by Auch-Auch** [comment]
For what we need coordinator ID?

**Comment by lemontree210** [comment]
> Why do we need coordinator ID?

Thanks, it was a typo :) student ID of course
