### ISSUE TITLE
API view: add student that accepted the offer to the existing group

### ISSUE THREAD

**Issue by lemontree210** [samanthasgroup/django-webapps#299]
This is a follow-up on #298 

When a coordinator from dashboard sends a request stating that a student that was earlier offered to join a group has accepted this offer:

## Add new log event type to `CoordinatorLogEventType`:

```py
    ADDED_STUDENT_TO_EXISTING_GROUP = (
        "added_student_to_existing group",
        "Added student to a group that was already studying",
    )
```

## Create log events

Types of `LogEvent`s to be created:

- coordinator(s): `ADDED_STUDENT_TO_EXISTING_GROUP`
- student: `STUDY_START`

## Set statuses
- student: set `project_status` to `STUDYING`, `situational_status` to `""` (blank)

> [!Note]
> Remember about `status_since` :)

**Comment by Auch-Auch** [comment]
If I understand correctly, we need to get group from log events?

**Comment by lemontree210** [comment]
> If I understand correctly, we need to get group from log events?

I think we'll just get student ID and group ID from the request, like in #298
