### ISSUE TITLE
API view: `Student` or `Teacher` is expelled from the project

### ISSUE THREAD

**Issue by lemontree210** [samanthasgroup/django-webapps#312]
When a coordinator (from dashboard) sends a request stating that a student or a teacher is to be permanently expelled from the project (not from just one group):

## Create log events

Type of `LogEvent` to be created: `EXPELLED`

## Create/change other objects:  

Remove from all groups by moving all `.groups()` to `.groups_former()`.

## Set status

`projects_status` to `BANNED`, `situational_status` to `""`.

Remember to update `status_since` to current time in UTC in objects (where applicable).

**Comment by Auch-Auch** [comment]
Why do we have `BANNED` for student and `EXPELLED` for teacher? :)
