### ISSUE TITLE
API view: oral interview successful, can wait for group

### ISSUE THREAD

**Issue by lemontree210** [samanthasgroup/django-webapps#320]
Some students (e.g. those that can't read or haven't learned English long enough) require a one-to-one interview. The student's language level is determined in this interview, then they can be put in the waiting queue.

A coordinator send from dashboard a request stating that the given `Student` has a given language level and can be put into the queue. The data in a `POST` request must include ID of `LanguageAndLevel` object.

## Check `Student`'s `project_status`

If the given `Student`'s `project_status` is not `NEEDS_INTERVIEW_TO_DETERMINE_LEVEL`, this is a wrong request.

## Change objects

Create a new many-to-many connection between `Student` and `LanguageAndLevel` by adding the `LanguageAndLevel` object to `.teaching_languages_and_levels`.

> [!NOTE] 
> Most likely all students will only be allowed to study in one group, but the database was designed to be more flexible and to technically allow several groups.

## Set status

Set `project_status` to `NO_GROUP_YET`

Remember to update `status_since` to current time in UTC in objects (where applicable).

## Create log events

Add log event of type `AWAITING_OFFER`
(**TODO:** check what event type is created when student is created through bot)

**Comment by Auch-Auch** [comment]
No log events are created on student creation
