### ISSUE TITLE
Create log events when new coordinator, student or teacher are created

### ISSUE THREAD

**Issue by lemontree210** [samanthasgroup/django-webapps#323]
Right now instances of `Coordinator`, `Student` and `Teacher` are created with the correct `project_status`, but we also need to create log events.

- `Coordinator`: `APPLIED`
- `Students`: `REGISTERED`
- `Teacher`: `REGISTERED`

It's OK to create two log events at the same time, e.g. for a `Student` that has a level determined and doesn't need any oral interview, we can create two log events right away: `REGISTERED` and `AWAITING_OFFER` (same for `Teacher`). It still makes sense especially for `Student` because for students that need oral interview, log event of type `REGISTERED` will not be immediately followed by log event of type `AWAITING_OFFER`.

Also, please check that `Group` gets a log event of type `FORMED` when it's created.

**Comment by Auch-Auch** [comment]
Currently we can not create a student or teacher without language level

**Comment by lemontree210** [comment]
> Currently we can not create a student or teacher without language level

language and level should definitely remain required for teachers. As for student... I'm really not sure what the best way is. Possible solutions:

1. check for combination of empty level and `project_status` being `NEEDS_INTERVIEW_TO_DETERMINE_LEVEL` (see https://github.com/samanthasgroup/django-webapps/pull/329#discussion_r1375405352)
2. set `project_status` to `NEEDS_INTERVIEW_TO_DETERMINE_LEVEL` to `True` automatically if no language level is passed
3. add another row to `LanguageAndLevel` for each language: "unknown" or "TBD" or something. Require the client to send this level if no level can be set. Then language and level can remain required. Automatically set `project_status` to `NEEDS_INTERVIEW_TO_DETERMINE_LEVEL` if such level is received from the bot.

In general, I start thinking that it's wrong to require the bot to send `project_status` to backend and that it instead should be set automatically.

I'll think about a compromise that would allow to leave more intrusive changes in the backlog for now.

**Comment by Auch-Auch** [comment]
Hmm, not sure there is any difference between options 2 and 3. Option 3 might make things complicated
