### ISSUE TITLE
Add version control for model instances

### ISSUE THREAD

**Issue by lemontree210** [samanthasgroup/django-webapps#332]
In our internal discussion, taking into consideration the active maintainable status of the project, we decided to use [django-reversion](https://github.com/etianen/django-reversion).

Ideally, even when changes are made to the model instances via API (from dashboard and bot), new revision should be created, if possible. But at least for those that are created in the admin interface.

@dont-text-me I don't think that we need to implement the functionality for reverting changes in the dashboard, at least not in the MVP. For now, it will be only available to the admins in the admin site.

**Comment by Roxe322** [comment]
@lemontree210 Which particular models we should control? Or all used in admin?

**Comment by lemontree210** [comment]
> @lemontree210 Which particular models we should control? Or all used in admin?

I think we can follow the logic that we should be able to correct anything that an admin or a coordinator can erroneously change (and the latter is a subset of the former), so yes, everything that is changeable in admin site.

**Comment by lemontree210** [comment]
> @lemontree210 Which particular models we should control? Or all used in admin?

Ideally we should be able to undo complex actions, e.g. if a student was erroneously transferred from group to group, then two groups change and log event is created. So reverting to a previous state would mean changing two groups and removing a log event. But if that's not available out of the box (and I doubt it is), then we'll just tell the admins to transfer the student right back in such case.

Our minimal and post important task is to prevent irreversible changes in fields of instances.
