### ISSUE TITLE
Admin site: Cosmetic changes to actions interface in table of coordinators

### ISSUE THREAD

**Issue by lemontree210** [samanthasgroup/django-webapps#413]
After #268 , owners requested some cosmetic changes to the "actions" interface.

- in the "Group" drop-down list, group names are too verbose. Leave only group ID, language/level, coordinator(s). 
For example: `1: English A2, (coords 2: Johns Smith, 3: Peter Powell)`*
- rename "Go" button into "Apply selected action"
- change order: 1st line - Group, 2nd line - Action, 3rd line - button

\* representation of a person as `id: first name last name` is a default `__str__()` representation of `Person` now, AFAIR

**Comment by Auch-Auch** [comment]
Regarding last two points I am not sure there is a simple way to do it, most likely only via custom templates, also not sure if Group action works at all, not sure why it is needed there in the first place

**Comment by Auch-Auch** [comment]
Looks like a backlog task for me :), but @lemontree210  I would look at the group action, how is it supposed to work?

**Comment by lemontree210** [comment]
> Looks like a backlog task for me :)

I know :) But I understand that the owners need to have all buttons and drop-down lists at the least surprising places. They will be using these tools quite often and they should be as clearly and obviously placed and named as possible

**Comment by lemontree210** [comment]
> not sure if Group action works at all, not sure why it is needed there in the first place

Some events with `Coordinator` affect only this coordinator (e.g. gone on leave, left project). Others affect some group as well: e.g. "took new group", "requested transfer" or "took transferred group" events require information on which `Group` the coordinator will be transferred to, which one did they take etc.

**Comment by lemontree210** [comment]
@Auch-Auch sorry for the late reply
