### ISSUE TITLE
Create populators for groups

### ISSUE THREAD

**Issue by lemontree210** [samanthasgroup/django-webapps#454]
The main problem to solve to find students, teachers and coordinators for groups by their old IDs (SID, TID and CID respectively) so they can be "attached" to the group being created.

@Auch-Auch maybe you will decide to make some changes to their populators as well (e.g. introduce some file that matches old IDs to new ones).

**Comment by Auch-Auch** [comment]
Should we create groups or only collect some metadata? Should we create the group even if it has already ended?

**Comment by lemontree210** [comment]
I'm sure that we need to re-create groups that are currently underway. Maybe I didn't understand the "only metadata" option.
Good question about finished/canceled groups, I've posted a question in our chat with owners.

**Comment by lemontree210** [comment]
@Auch-Auch is it fair though to consider this issue closed already?

**Comment by Auch-Auch** [comment]
Yes, we can close, in general all scripts are ready, if we will find some bugs we will create a separate ticket
