### ISSUE TITLE
API views: Add `Student` to existing `Group` after it started classes

### ISSUE THREAD

**Issue by lemontree210** [samanthasgroup/django-webapps#493]
The basic functionality for adding `Student` to `Group` is provided by standard viewsets. But we need to log this:
- create a "group offered" event for this `Student`, then an event when they join the group (which type of event exactly?)
- create an event called something like "student joined" for `Group`.

I guess that since we need logging (thanks @Auch-Auch for pointing that out), there will have to be a separate action?

**Comment by Auch-Auch** [comment]
We also have patch and put, the list in https://www.django-rest-framework.org/api-guide/viewsets/#modelviewset but it is only for internal usage (not for dashboard), there is no need actually to include anything else except new student list. And this will not be logged I think

**Comment by Auch-Auch** [comment]
Wait, not sure I get it, we have two endpoints: accepted_offered_group, offer_join_group which are responsible for handling student status. So it is a kind of design question at which endpoints we should handle student status/group. E.g. we can add Student to the group when accepted_offered_group is triggered but then we have to modify Group at the student Viewset (that is not always good). Or we can add to the group at group Viewset and update Student. Or there is much more that can be done, the question is that exactly we want to achieve

**Comment by lemontree210** [comment]
OK, great, I just forgot that our actions for offering and accepting the offered `Group` are universal and can be used for the case when we want to offer `Student` to join existing `Group`.

**Comment by lemontree210** [comment]
Closing this as already implemented. I will mention creating a new `GroupLogEvent` in a separate issue
