### ISSUE TITLE
Add `role_comment` `CharField` to `Coordinator`

### ISSUE THREAD

**Issue by lemontree210** [samanthasgroup/django-webapps#503]
This field will include a short phrase describing `Coordinator`s main role (e.g. "speaking club", "CV" etc.)

Display name for admin site should be "role"

**Comment by Auch-Auch** [comment]
ENUM or any charfield?

**Comment by lemontree210** [comment]
> ENUM or any charfield?

How did I manage to miss this question and not reply to it? Unbelievable 😢 
Any `CharField`
